namespace EnumerableToolkit.Builder.AsyncBlocks
{
    /// <summary>
    /// Represents the basic building block of <see cref="IAsyncEnumerableBuilder{T}"/>s.
    /// </summary>
    /// <typeparam name="T">The type of the items in the generated sequence.</typeparam>
    public abstract class AsyncBuildingBlock<T> : IAsyncBuildingBlock<T>
    {
        /// <inheritdoc/>
        public abstract IAsyncEnumerable<T> Apply(IAsyncEnumerable<T> current);

        IAsyncEnumerable<T> IAsyncParametrizedBuildingBlock<T, object>.Apply(IAsyncEnumerable<T> current, object parameters)
            => Apply(current);
    }

    /// <summary>
    /// Defines the interface for a basic async building block
    /// that can be applied to incrementally generate an async sequence.
    /// </summary>
    /// <typeparam name="T">The type of the items in the generated sequence.</typeparam>
    public interface IAsyncBuildingBlock<T> : IAsyncParametrizedBuildingBlock<T, object>
    {
        /// <summary>
        /// Applies this <see cref="IAsyncEnumerableBuilder{T}"/> building block to the given async sequence.
        /// </summary>
        /// <param name="current">The current async sequence generated by the builder.</param>
        /// <returns>The new async sequence with this building block applied.</returns>
        public IAsyncEnumerable<T> Apply(IAsyncEnumerable<T> current);
    }

    /// <summary>
    /// Defines the interface for a parametrized building block
    /// that can be applied to incrementally generate an async sequence.
    /// </summary>
    /// <typeparam name="T">The type of the items in the generated async sequence.</typeparam>
    /// <typeparam name="TParameters">The type of the parameters for generating an async sequence.</typeparam>
    public interface IAsyncParametrizedBuildingBlock<T, in TParameters>
    {
        /// <summary>
        /// Applies this <see cref="IAsyncParametrizedEnumerableBuilder{T, TParameters}"/> building block to the given async sequence.
        /// </summary>
        /// <param name="current">The current async sequence generated by the builder.</param>
        /// <param name="parameters">The parameters to generate a sequence with.</param>
        /// <returns>The new async sequence with this building block applied.</returns>
        public IAsyncEnumerable<T> Apply(IAsyncEnumerable<T> current, TParameters parameters);
    }
}