namespace EnumerableToolkit.Builder.AsyncBlocks
{
    /// <summary>
    /// Represents the basic building block of the <see cref="AsyncEnumerableBuilder{T}"/>.
    /// </summary>
    /// <typeparam name="T">The type of the items in the generated sequence.</typeparam>
    public abstract class AsyncBuildingBlock<T>
    {
        /// <summary>
        /// Applies this <see cref="AsyncEnumerableBuilder{T}"/> building block to the given sequence.
        /// </summary>
        /// <param name="current">The current sequence generated by the builder.</param>
        /// <returns>The new sequence with this building block applied.</returns>
        public abstract IAsyncEnumerable<T> Apply(IAsyncEnumerable<T> current);
    }
}