namespace EnumerableToolkit.Builder.Blocks
{
    /// <summary>
    /// Represents the basic building block of the <see cref="EnumerableBuilder{T}"/>.
    /// </summary>
    /// <typeparam name="T">The type of the items in the generated sequence.</typeparam>
    public abstract class BuildingBlock<T>
    {
        /// <summary>
        /// Applies this <see cref="EnumerableBuilder{T}"/> building block to the given sequence.
        /// </summary>
        /// <param name="current">The current sequence generated by the builder.</param>
        /// <returns>The new sequence with this building block applied.</returns>
        public abstract IEnumerable<T> Apply(IEnumerable<T> current);
    }
}